[Distribution]
Distribution=postmarketos
Release=edge

[Config]
PassEnvironment=PMOS_DEVICE PMOS_VARIANT CI RELEASE
# Multi-image builds auto-discover mkosi.images/ subdirectories

[Build]
Environment=PMOS_DEVICE=qcom-sc7180-lenovo-thinkpad-x13s
PMOS_VARIANT=gnome
RELEASE=edge
History=yes
CacheDirectory=mkosi.cache
Incremental=no

[Output]
OutputDirectory=mkosi.output/%i
SplitArtifacts=partitions,uki
