[Distribution]
Distribution=postmarketos

[Output]
ImageId=bluefin-system-files
Format=directory

[Content]
# Extract Bluefin common OCI and layer system files
Environment=BLUEFIN_IMAGE_REF=ghcr.io/projectbluefin/common:latest
