[Include]
Include=%C/extension-compression.conf

[Build]
Environment=
	SYSEXT_SCOPE=system
	# Enable compression for erofs, lz4 is same as usr partition for OS
	# images
	SYSTEMD_REPART_MKFS_OPTIONS_EROFS="-zlz4 -b 4096"

[Output]
Output=%i_%v.%I-%a
Format=sysext

[Content]
FinalizeScripts=../../scripts/extension-finalize

[Validation]
# Only generate hash, don't sign. Signing requires enabling
# CONFIG_DM_VERITY_VERIFY_ROOTHASH_SIG and embedding keys in the kernel (or
# giving it a sep. keyring)
Verity=hash
