[Output]
Format=directory

[Content]
CleanPackageMetadata=no
Packages=
	systemd
	base-files
	xwayland
	weston
	gnome-shell
	gnome-terminal
	gnome-control-center
	eog
	fd-find
	curl
	wget
	git
	zsh
	fish
	tmux
