[Distribution]
Distribution=postmarketos
Release=edge

[Output]
Format=directory

[Content]
CleanPackageMetadata=no
Packages=
postmarketos-base
postmarketos-duranium-base
postmarketos-duranium-bootloader

[Validation]
Verity=no
