[Output]
Format=directory

[Content]
CleanPackageMetadata=no
Packages=
	linux-image-arm64
	linux-firmware
	systemd
	systemd-boot
	grub-efi-arm64-signed
	shim-signed
	base-files
	firmware-linux
	xwayland
	weston
RemovePackages=
	gnome-software-plugin-apk
